downloader/urls.py
from django.urls import path

from .tasks import(
    begin_auth,
    authorize,
)

from .views import (
    LoginView,
    SearchView,
    SearchResultsView,
    SearchHistoryView,
    PreviousSearchView,
    RemoveQueriesView,
    GenerateFilesView,
    DownloadView,
    LogoutView
)

app_name = 'downloader'

urlpatterns = [
    path('begin-authorization/', begin_auth, name='begin-authorization'),
    path('authorize/', authorize, name='authorize'),
    path('', LoginView.as_view(), name='login'),

    path('search/', SearchView.as_view(), name='search-main'),
    path('search/results/<int:pk>/', SearchResultsView.as_view(), name='search-results'),
    path('search/<str:type>/', SearchHistoryView.as_view(), name='search-history-or-favorites'),
    path('search/history/<int:pk>/', PreviousSearchView.as_view(), name='previous-search-main'),
    path('search/history/remove/', RemoveQueriesView.as_view(), name='remove-queries'),

    path('generate/<int:pk>', GenerateFilesView.as_view(), name='generate-files'),
    path('download/<int:pk>/<str:tmp>', DownloadView.as_view(), name='download'),
    path('logout/', LogoutView.as_view(), name='logout')
]

templates/authorization/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Login</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
  <div class="page-content-wrapper">
    <div id="navbar-wrapper">
      <nav class="navbar navbar-expand-xl d-flex justify-content-between" id="navbar">
        <div class="navbar-brand ">
          <svg id="download-icon" xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
            class="bi bi-download" viewBox="0 0 16 16">
            <path
              d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z" />
            <path
              d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z" />
          </svg>
          Reddit Downloader
        </div>
      </nav>
    </div>
  
    <div class="container login-wrapper">
      <div class="container section-header">
        <h3>
          Log in
        </h3>
      </div>
      <div class="container">
        <p><a href="{% url 'downloader:begin-authorization' %}">Click here</a> to log in through Reddit</p>
        <p>Or <a href="{% url 'downloader:search-main' %}">continue to search</a> without logging in.</p>
      </div>
    </div>
  </div>