downloader/urls.py
from django.urls import path

from .tasks import(
    begin_auth,
    authorize,
)

from .views import (
    LoginView,
    SearchView,
    SearchResultsView,
    SearchHistoryView,
    PreviousSearchView,
    RemoveQueriesView,
    GenerateFilesView,
    DownloadView,
    LogoutView
)

app_name = 'downloader'

urlpatterns = [
    path('begin-authorization/', begin_auth, name='begin-authorization'),
    path('authorize/', authorize, name='authorize'),
    path('', LoginView.as_view(), name='login'),

    path('search/', SearchView.as_view(), name='search-main'),
    path('search/results/<int:pk>/', SearchResultsView.as_view(), name='search-results'),
    path('search/<str:type>/', SearchHistoryView.as_view(), name='search-history-or-favorites'),
    path('search/history/<int:pk>/', PreviousSearchView.as_view(), name='previous-search-main'),
    path('search/history/remove/', RemoveQueriesView.as_view(), name='remove-queries'),

    path('generate/<int:pk>', GenerateFilesView.as_view(), name='generate-files'),
    path('download/<int:pk>/<str:tmp>', DownloadView.as_view(), name='download'),
    path('logout/', LogoutView.as_view(), name='logout')
]

downloader/models.py
from django.db import models


class User(models.Model):
    username = models.CharField(max_length=20, primary_key=True)
    last_clear_datetime = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.username


class SearchQuery(models.Model):
    PRAW_SORT_CHOICES = (
        ('relevance', 'Relevance'),
        ('hot', 'Hot'),
        ('top', 'Top'),
        ('new', 'New'),
        ('comments', 'Comments'),
        ('controversial', 'Controversial'),
        ('rising', 'Rising'),
        ('random_rising', 'Random Rising')
    )
    PSAW_SORT_CHOICES = (
        ('created_utc', 'Date'),
        ('num_comments', 'Number of comments'),
        ('score', 'Score')
    )
    TIME_FILTER_CHOICES = (
        ('all', 'All Time'),
        ('hour', 'Past Hour'),
        ('day', 'Past 24 Hours'),
        ('month', 'Past Month'),
        ('year', 'Past Year'),
    )
    SYNTAX_CHOICES = (
        ('lucene', 'Lucene'),
        ('cloudsearch', 'Cloudsearch'),
        ('plain', 'Plain')
    )

    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    url = models.URLField(max_length=250, blank=True)
    terms = models.CharField(
        max_length=512, 
        blank=True
    )
    subreddit = models.CharField(
        max_length=250, 
        blank=True,  
        help_text="Comma separated: askreddit,askscience <br>Use ! to exclude: all,!askreddit"
    )
    syntax = models.CharField(
        max_length=11,
        choices=SYNTAX_CHOICES,
        default='lucene'
    )
    limit = models.PositiveIntegerField(default=25)
    praw_sort = models.CharField(
        max_length=13,
        choices=PRAW_SORT_CHOICES,
        blank=True
    )
    time_filter = models.CharField(
        max_length=5,
        choices=TIME_FILTER_CHOICES,
        blank=True
    )
    start_date = models.DateTimeField(
        blank=True, 
        null=True, 
        help_text="(YYYY-MM-DD [HH:MM:SS])"
    )
    end_date = models.DateTimeField(blank=True, null=True)
    psaw_sort = models.CharField(
        max_length=18,
        choices=PSAW_SORT_CHOICES,
        blank=True
    )
    date_created = models.DateTimeField(auto_now=True)
    favorite = models.BooleanField(default=False)

    class Meta:
      verbose_name_plural = "Search queries"

downloader/views.py
from django.contrib import messages
from django.contrib.auth.mixins import UserPassesTestMixin
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.views.generic.base import View 
from django.views.generic import ( 
    FormView,
    DetailView
)
from reddit_downloader.settings import production as settings
from .export import (
    download_results
)
from .forms import (
    SearchForm,
    DownloadForm
)
from .models import (
    User,
    SearchQuery,
)
from .tasks import (
    get_results,
    get_submission_data_by_url,
)
import json
import os
import shutil
import zipfile


class LoginView(View):
    template_name = 'authorization/login.html'

    def get(self, request, *args, **kwargs):
        if request.session.get('authenticated', False):
            return redirect(reverse('downloader:search-main'))
        else:
            return render(request, self.template_name, {})


class SearchView(View):
    template_name = 'downloader/search_view.html'
    model = SearchQuery
    form_class = SearchForm

    def get(self, request, *args, **kwargs):
        auth = request.session.get('authenticated', False)
        context = {
            'form': self.form_class,
            'authenticated': auth
            }
        return render(request, self.template_name, context)
    
    def post(self, request, *args, **kwargs):
        # If re-doing a search, create a new query from the existing one.
        id_ = request.POST.get('redo', None)
        if id_ is not None:
            old_query = SearchQuery.objects.get(pk=id_)
            new_query = old_query
            new_query.pk = None
            new_query.save()
        else:
            form = self.form_class(data=request.POST)
            if form.is_valid():
                query = form.save(commit=False)
                if request.session.get('authenticated', False) is True:
                    # Add user to search query object
                    username = self.request.session["current_user"]
                    query.user = User.objects.get(username=username)
                query.save()
            else:
                auth = request.session.get('authenticated', False)
                context = {
                    'form': form,
                    'authenticated': auth}
                return render(self.request, self.template_name, context)

        return redirect(reverse('downloader:search-results', kwargs={'pk': query.pk}))


class SearchResultsView(View):
    """Display the results of a Search Query."""
    template_name = 'downloader/search_results.html'
    download_form = DownloadForm

    def get_object(self, *args, **kwargs):
        id_ = self.kwargs.get('pk')
        return get_object_or_404(SearchQuery, pk=id_)

    def get(self, request, *args, **kwargs):
        query = self.get_object()
        if query.url:
            results = get_submission_data_by_url(query.url)
        else:
            results, non_existent_subreddits, forbidden_subreddits = get_results(query)

            # If any subreddits do not exist or are forbidden, inform the user that they were ignored.
            if non_existent_subreddits:
                subs_str = ', '.join(non_existent_subreddits)
                messages.info(request, f"The following subreddits do not exist: {subs_str}.")
            
            if forbidden_subreddits:
                subs_str = ', '.join(forbidden_subreddits)
                messages.info(request, f"The following subreddits are forbidden: {subs_str}.")

        auth = request.session.get('authenticated', False)
        context = {
            'query': query,
            'results': results,
            'form': self.download_form,
            'authenticated': auth
        }
        return render(request, self.template_name, context)


class PreviousSearchView(FormView):
    template_name = 'downloader/search_view.html'
    model = SearchQuery

    def get_object(self, *args, **kwargs):
        id_ = self.kwargs.get('pk')
        return get_object_or_404(SearchQuery, pk=id_)

    def get(self, request, *args, **kwargs):
        q = self.get_object()
        form = SearchForm(instance=q, edit=True)
        auth = request.session.get('authenticated', False)
        context = {
            'form': form,
            'authenticated': auth
        }
        return render(request, self.template_name, context)


class SearchHistoryView(UserPassesTestMixin, DetailView):
    template_name = 'downloader/search_history_or_faves.html'

    def test_func(self):
        return self.request.session.get('authenticated', False)

    def get(self, request, *args, **kwargs):
        username = request.session["current_user"]
        last_clear = User.objects.get(username=username).last_clear_datetime
        type_ = self.kwargs.get('type')
        if type_ == 'history':
            queries = SearchQuery.objects.filter(user=username, date_created__gt=last_clear).order_by('-date_created')
        else:
            queries = SearchQuery.objects.filter(user=username, favorite=True).order_by('-date_created')

        auth = request.session.get('authenticated', False)
        context = {
            'queries': queries,
            'type': type_,
            'authenticated': auth
        }
        return render(request, self.template_name, context)


class RemoveQueriesView(UserPassesTestMixin, View):

    def test_func(self):
        return self.request.session.get('authenticated', False)

    def post(self, request, *args, **kwargs):
        if request.is_ajax:
            id_str = request.POST.get('query_ids')
            ids = json.loads(id_str)
            objs = SearchQuery.objects.filter(pk__in=ids)

            username = request.session.get('current_user')
            user = User.objects.get(username=username)

            if 'remove-queries' in request.POST:
                # Delete all queries except those marked as favorites.
                objs.filter(favorite=False).delete()
                # Update the user's last_clear_datetime
                user.last_clear_datetime = timezone.now()
                user.save()
            elif 'remove-faves' in request.POST:
                objs.filter(date_created__lt=user.last_clear_datetime).delete()
                objs.filter(date_created__gt=user.last_clear_datetime).update(favorite=False)
            elif 'add-faves' in request.POST:
                objs.update(favorite=True)
            else:
                return JsonResponse({'error': 'Something went wrong'}, status=400)
            return JsonResponse({}, status=200)
        else:
            return JsonResponse({'error': 'Request is not ajax.'}, status=400)    


class GenerateFilesView(FormView):
    form_class = DownloadForm

    def get_object(self, *args, **kwargs):
        id_ = self.kwargs.get('pk')
        return get_object_or_404(SearchQuery, pk=id_)

    def post(self, request, *args, **kwargs):
        query = self.get_object()
        if request.is_ajax:
            form = DownloadForm(data=request.POST)
            if form.is_valid():
                sub_str = request.POST.get('sub_ids')
                sub_ids = json.loads(sub_str)
                tmp_dirname = download_results(query, form.cleaned_data, sub_ids)

                # Return the url that generates/downloads the files in the response
                url = reverse('downloader:download', kwargs={'pk': query.pk, 'tmp':tmp_dirname})
                return JsonResponse({'url': url}, status=200)
            else:
                return JsonResponse({'error': form.errors.as_json()}, status=400)
        else:
            return JsonResponse({'error': 'Request is not ajax.'}, status=400)


class DownloadView(View):

    def get_object(self, *args, **kwargs):
        id_ = self.kwargs.get('pk')
        return get_object_or_404(SearchQuery, pk=id_)

    def get(self, request, *args, **kwargs):
        dirname = self.kwargs.get('tmp')
        tmp_path = os.path.join(settings.MEDIA_ROOT, dirname)
        zname = 'results.zip'

        response = HttpResponse(content_type='application/zip')
        with zipfile.ZipFile(response, 'w') as f:
            # Place each generated file into the zip file
            for folder_name, sub_folders, filenames in os.walk(tmp_path):
                for filename in filenames:
                    filepath = os.path.join(folder_name, filename)
                    zip_path = os.path.join(folder_name.split('/')[-1], os.path.basename(filepath))
                    f.write(filepath, zip_path)

        response['Content-Disposition'] = 'attachment; filename={}'.format(zname)
        # Delete the generated files
        shutil.rmtree(tmp_path)

        return response


class LogoutView(View):

    def get(self, request, *args, **kwargs):
        request.session.clear()
        return redirect(reverse('downloader:login'))

downloader/templates/downloader/search_history_or_faves.html
{% extends 'base.html' %}
{% load string_filters %}
{% block title %}
  {% if type == 'favorites' %}
    Favorites
  {% else %}
    Search History
  {% endif %}
{% endblock %}
{% block content %}
<div class="table-form-container px-3 pb-3">
  <div class="section-header">
    {% if type == 'favorites' %}
    <h3>Favorites</h3>
    {% else %}
    <h3>Search History</h3>
    {% endif %}
  </div>
  {% if queries %}
  <p class="help-text">
    Hold ctrl/cmd to select or deselect individual items. Hold shift to select or deselect a range of items.
  </p>
  <div class="table-container">
    <table class="table table-sm table-striped table-bordered">
      <thead class="thead-dark">
        <tr>
          <th></th>
          <th>Query</th>
          <th>Subreddit(s)</th>
          <th>Sort</th>
          <th>Limit</th>
          <th>Time Filter</th>
          <th>Date searched</th>
          <th>options</th>
          <th>id</th>
        </tr>
      </thead>
      <tbody>
        {% for query in queries %}
        <tr>
          <td class="align-middle"></td>
          <td class="align-middle text-wrap">{{query.terms}}</td>
          <td class="align-middle text-wrap">{{query.subreddit|add_spaces}}</td>
          <td class="align-middle">
            {% if query.praw_sort %}
            {{query.get_praw_sort_display}}
            {% elif query.psaw_sort %}
            {{query.get_psaw_sort_display}}
            {% endif %}
          </td>
          <td class="align-middle">{{query.limit}}</td>
          <td class="align-middle">{{query.time_filter}}</td>
          <td class="align-middle">{{query.date_created}}</td>
          <td class="align-middle">
            <div>
              <form action="{% url 'downloader:search-main' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="redo" value="{{query.pk}}">
                <div>
                  <button class="link-btn text-nowrap" type="submit">Search again</button>
                </div>
                <div>
                  <a href="{% url 'downloader:previous-search-main' pk=query.pk %}">Details</a>
                </div>
              </form>
            </div>
          </td>
          <td>{{query.pk}}</td>
        </tr>
        {% endfor %}
    </table>
  </div>
  <div class="pt-5 pb-3 d-flex justify-content-center">
    <form id="remove-queries-form" action="{% url 'downloader:remove-queries' %}" method="POST">
      {% csrf_token %}
      {% if type == 'favorites' %}
      <input type="submit" class="rm-btn btn btn-primary" name="remove-faves" value="Remove selected queries from favorites"></button>
      {% else %}
      <input type="submit" class="rm-btn btn btn-primary" name="remove-queries" value="Remove selected queries"></button>
      <input type="submit" class="rm-btn btn btn-primary" name="add-faves" value="Add selected queries to favorites"></button>
      {% endif %}
  </div>
  {% else %}
  <div class="empty-msg">
    {% if type == 'favorites' %}
    <p class="empty-msg">You currently have no favorites.</p>
    {% else %}
    <p class="empty-msg">There are no searches in your history.</p>
    {% endif %}
  </div>
  {% endif %}
</div>
{% endblock %}

downloader/templates/downloader/search_results.html
{% extends 'base.html' %}
{% block title %}Search Results{% endblock %}
{% block content %}
<div class="table-form-container px-3 pb-3">
  <div class="section-header">
    <h3>Search Results</h3>
  </div>
  {% if results %}
  <p class="help-text">
    Hold ctrl/cmd to select or deselect individual items. Hold shift to select or deselect a range of items.
  </p>
  <div class="table-container">
    <table class="table table-sm table-striped table-bordered">
      <thead class="thead-dark">
        <tr>
          <th></th>
          <th>Title</th>
          <th>Score</th>
          <th>Permalink</th>
          <th>External URL</th>
          <th>Comments</th>
          <th>Created</th>
          <th>Body</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for sub in results %}
        <tr>
          <td></td>
          <td class="align-middle text-wrap">{{sub.title|truncatechars:200}}</td>
          <td class="align-middle">{{sub.score}}</td>
          <td class="align-middle text-break">{{sub.permalink|urlizetrunc:50}}</td>
          <td class="align-middle text-break">{{sub.url|urlizetrunc:50}}</td>
          <td class="align-middle">{{sub.num_comments}}</td>
          <td class="align-middle">{{sub.date}}</td>
          <td class="align-middle text-wrap">{{sub.selftext|truncatechars:200}}</td>
          <td>{{sub.id}}</td>
        </tr>
        {% endfor %}
    </table>
  </div>
  <div class="opt-container pt-4" id="download-options-container">
    <div class="section-header">
      <h3>Download Options</h3>
    </div>
    <div class="message-wrapper" id="download-message-wrapper" style="display:none;">
      <span>Your download has begun</span>
    </div>
    <ul class="help-text">
      <li>
        Select 'submission' or 'comments' to get metadata, then select the desired corresponding fields. Select
        'external' to get external files (images only).
      </li>
      <li>
        Hold ctrl/cmd to select or deselect individual fields. Hold shift to select or deselect a range of fields.
      </li>
    </ul>
    <form id="download-form" action="{% url 'downloader:generate-files' pk=query.pk %}">
      {% csrf_token %}
      <div class="d-flex flex-wrap justify-content-around mt-5">
        <div class="mr-3">
          <p>{{form.get_submission_data}} {{form.get_submission_data.label}}</p>
          <p>{{form.get_comment_data}} {{form.get_comment_data.label}}</p>
          <p>{{form.get_external_data}} {{form.get_external_data.label}}</p>
        </div>
        <div class="mx-3" id="submission-fields">
          <p>{{form.submission_field_options.label}}</p>
          <p>{{form.submission_field_options}}</p>
        </div>
        <div class="mx-3" id="comment-fields">
          <p>{{form.comment_field_options.label}}</p>
          <p>{{form.comment_field_options}}</p>
        </div>
        <div class="mx-3" id="comment-sort">
          <p>{{form.comment_sort_option.label}}</p>
          <p>{{form.comment_sort_option}}</p>
        </div>
        <div class="mx-3" id="comment-limit">
          <p>{{form.comment_limit.label}}</p>
          <p>{{form.comment_limit}}</p>
          <p>{{form.comment_limit.help_text}}</p>
        </div>
      </div>
      <div class="btn-container d-flex justify-content-center">
        <button type="submit" class="btn btn-primary" id="download-btn">
          <i class="fa fa-refresh fa-spin loading-icon" style="display:none"></i> Download</button>
      </div>
    </form>
  </div>
  {% else %}
  <div class="empty-msg">
    <p class="empty-msg">No results match your query</p>
  </div>
  {% endif %}
</div>
{% endblock %}

downloader/templates/downloader/search_view.html
{% extends 'base.html' %}
{% block title %}Search{% endblock %}
{% block content %}

<div class="container" id="search-form-wrapper">
  <div class="container section-header">
    <h3>Search Reddit</h3>
  </div>
  <form action="{% url 'downloader:search-main' %}" method='POST'>
    {% csrf_token %}
    <div class="container">
      <p>Please enter a URL below to search for a single submission, or provide search criteria. Search terms may be required depending on the selected sort option.</p>
      <div class="row mt-5">
        <div class="col">
          {{form.url_select}}
          {{form.url.label}} {{form.url}}
          <p>{{form.url.errors}}</p>
        </div>
      </div>
      <div class="row mt-5">
        <div class="col">
          {{form.terms_select}}
          {{form.terms.label}} {{form.terms}}
          <p>{{form.terms.errors}}</p>
        </div>
      </div>
      <div class="row mt-5">
        <div class="col">
          <p>{{form.subreddit.label}} {{form.subreddit}}</p>
          {% autoescape off%}{{form.subreddit.help_text}}{% endautoescape %}
          <p>{{form.subreddit.errors}}</p>
        </div>
        <div class="col">
          <p>{{form.syntax.label}} {{form.syntax}}</p>
          <p>{{form.syntax.errors}}</p>
        </div>
      </div>
      <div class="row my-5">
        <div class="col">
          <p>{{form.limit.label}} {{form.limit}}</p>
          <p>{{form.limit.errors}}</p>
        </div>
      </div>
      <div class="pt-3 pb-5" id="time_options">
        <div class="mb-5">
          <p>Select either a standard Reddit time filter and sort, or provide a date a range with other sort.</p>
        </div>
        <div class="row">
          <div class="col-auto">
            {{form.time_filter_select}}
          </div>
          <div class="col">
            {{form.time_filter.label}} {{form.time_filter}}
            <p>{{form.time_filter.errors}}</p>
          </div>
          <div class="col">
            <p>Sort {{form.praw_sort}}</p>
            <p id="terms-warning" style="display:none;">Search terms will be ignored for this option</p>
            <p>{{form.praw_sort.errors}}</p>
          </div>
          <div class="col">
          </div>
        </div>
        <div class="row mt-5">
          <div class="col-auto">
            {{form.date_range_select}}
          </div>
          <div class="col">
            <p>{{form.start_date.label}} {{form.start_date.help_text}}</p>
            <p>{{form.start_date}}</p>
            <p>{{form.start_date.errors}}</p>
          </div>
          <div class="col">
            <p>{{form.end_date.label}}</p>
            <p>{{form.end_date}}</p>
            <p>{{form.end_date.errors}}</p>
          </div>
          <div class="col">
            <p>Sort</p>
            <p>{{form.psaw_sort}}</p>
            <p>{{form.psaw_sort.errors}}</p>
          </div>
        </div>
      </div>
      <p class="my-5">{{form.favorite}} Favorite this search</p>
      <div class="container btn-container d-flex justify-content-center">
        <button class="btn btn-success submit-btn" id="search_btn" type="submit">
          <i class="fa fa-refresh fa-spin loading-icon" style="display:none"></i> Search
        </button>
      </div>
    </div>
  </form>
</div>
{% endblock %}